### ISSUE TITLE
The Skin Manager goes back to version 1.5.0.0 after installing latest 2.0.1

### ISSUE THREAD

**Issue by vinayakv22** [danieladov/jellyfin-plugin-skin-manager#71] opened 2024-07-04 04:46 UTC
After installing the latest version 2.0.1 and restarting Jellyfin(to enable the plugin) the version goes to 1.5.0.0. Is jellyfin detecting it as higher version on the repo?

**Comment by KalebSchmidlkofer** [comment] 2024-07-31 09:33
+1

**Comment by vinayakv22** [comment] 2024-08-05 11:48
The only solution that I found was to rename the 2.0.1 package to 1.5.0.0. it would show as 1.5.0.0 but you'll have the latest version

**Comment by samrg123** [comment] 2024-08-05 19:04
Recommend moving this issue to a bug.
From some digging this issue is caused by an improperly built Jellyfin.Plugin.SkinManager.dll bundled in release version 2.0.1. The built dll still uses the old assembly version of 1.5.0.0 instead of 2.0.1.

When Jellfin loads the plugin at boot it uses the reported dll version instead of using the version in the Skin Manager meta.json file. This can results in broken references (such as a missing plugin image) which can be 'fixed' by changing the version in Skin Manager's meta.json file to 1.5.0.0 and creating a "Skin Manager_1.5.0.0" symbolic link that points to `Skin Manager_2.0.1` in the jellyfin plugin folder ("/config/plugins" on Linux).

**Comment by iamLazyCode** [comment] 2024-08-07 13:18
> Recommend moving this issue to a bug. From some digging this issue is caused by an improperly built Jellyfin.Plugin.SkinManager.dll bundled in release version 2.0.1. The built dll still uses the old assembly version of 1.5.0.0 instead of 2.0.1.
> 
> When Jellfin loads the plugin at boot it uses the reported dll version instead of using the version in the Skin Manager meta.json file. This can results in broken references (such as a missing plugin image) which can be 'fixed' by changing the version in Skin Manager's meta.json file to 1.5.0.0 and creating a "Skin Manager_1.5.0.0" symbolic link that points to `Skin Manager_2.0.1` in the jellyfin plugin folder ("/config/plugins" on Linux).

can you please fix it

**Comment by Daemonias** [comment] 2024-08-14 15:40
> > Recommend moving this issue to a bug. From some digging this issue is caused by an improperly built Jellyfin.Plugin.SkinManager.dll bundled in release version 2.0.1. The built dll still uses the old assembly version of 1.5.0.0 instead of 2.0.1.
> > When Jellfin loads the plugin at boot it uses the reported dll version instead of using the version in the Skin Manager meta.json file. This can results in broken references (such as a missing plugin image) which can be 'fixed' by changing the version in Skin Manager's meta.json file to 1.5.0.0 and creating a "Skin Manager_1.5.0.0" symbolic link that points to `Skin Manager_2.0.1` in the jellyfin plugin folder ("/config/plugins" on Linux).
> 
> can you please fix it

+1

**Comment by igiffrekt** [comment] 2024-09-04 09:49
Please fix it, same issue here

**Comment by igiffrekt** [comment] 2024-09-04 09:49
> The only solution that I found was to rename the 2.0.1 package to 1.5.0.0. it would show as 1.5.0.0 but you'll have the latest version

Can you please tell me how did you do that exactly? Would nice to have a workaround until it's fixed

**Comment by markalex2209** [comment] 2024-11-04 21:03
AFAICT, issue is caused by the dll version inside of release 2.0.1 still being 1.5.0.0. I guess during release somehow older version of dll was published.

@danieladov, can you please bump the version and trigger new release?

---
P.S. Image for skin not showing up in the plugin manager also caused by this. Jellyfin tries to fetch image from `/Plugins/e9ca8b8eca6d40e785dc58e536df8eb3/1.5.0.0/Image` but gets 404. And `/Plugins/e9ca8b8eca6d40e785dc58e536df8eb3/2.0.1/Image` get image normally.

**Comment by danieladov** [comment] 2024-11-04 23:14
Hi, I've just released a new version, it should be working now

**Comment by markalex2209** [comment] 2024-11-05 06:21
Yep, after update correct version is loaded:
![image](https://github.com/user-attachments/assets/5c0780a7-3dc2-403b-9c01-c18108eba047)
Also, image is showing up now)
![image](https://github.com/user-attachments/assets/4e47abb1-f45e-4ee4-86b1-3dc9d29eb5cc)

Thank you!

**Closed** 2024-11-05 09:42 UTC
